# Generated by Django 4.2.2 on 2023-07-23 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="engine",
            old_name="brand_model",
            new_name="engine_model",
        ),
    ]
