# Generated by Django 4.2.2 on 2023-07-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0003_staff_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="brand_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
